### ISSUE TITLE
SQL Plan Directive Objects spool file missing from eDB360, file 3b

### ISSUE THREAD

**Issue by sqldb360** [sqldb360/sqldb360#18] opened 2018-09-28 16:01 UTC
Under some unknown circumstances the spool file with SPD objects is missing from edb360 (file 3b).
Such info IS present in SQLd360 for specific SQLs

**Comment by abelmacias** [comment] 2019-01-04 00:54
caused by another non-displayable character issue now in 3b.

**Comment by mauropagano** [comment] 2019-01-04 05:25
@abelmacias , want to assign this one to yourself?

**Comment by mauropagano** [comment] 2019-01-10 21:02
Fixed in #33

**Closed as completed by mauropagano** 2019-01-10 21:02 UTC
Labels: bug, help wanted
